[package]
name = "matty"
description = "A neat matrix and vector library"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.17"

[features]
simd = [] # feature has no explicit dependencies
